use_frameworks!

platform :ios, '10.0'

target 'SDKPrivatePodTest_Example' do
  pod 'SDKPrivatePodTest', :path => '../'

  target 'SDKPrivatePodTest_Tests' do
    inherit! :search_paths

    
  end
end
